FROM UPSTREAM_REPO

ARG MYSQL_PACKAGE_VERSION=5.7.13-1
ENV MYSQL_PACKAGE_VERSION=$MYSQL_PACKAGE_VERSION
ENV PACKAGE_URL https://repo.mysql.com/yum/mysql-5.7-community/docker/x86_64/mysql-community-server-minimal-$MYSQL_PACKAGE_VERSION.el7.x86_64.rpm
ENV MYSQL_DATABASE db
ENV MYSQL_USER db
ENV MYSQL_PASSWORD db
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_MAX_ALLOWED_PACKET 16m

# Install server
RUN rpmkeys --import http://repo.mysql.com/RPM-GPG-KEY-mysql \
  && yum install -y $PACKAGE_URL \
  && yum install -y libpwquality \
  && rm -rf /var/cache/yum/* \
  && rm -rf /var/lib/mysql \
  && mkdir -p /var/lib/mysql

# Ensure there is no db from package installation
RUN mkdir /docker-entrypoint-initdb.data && \
  rm -rf /var/lib/mysql && \
  mkdir /var/lib/mysql

ADD files /
RUN chmod ugo+x /import.sh /healthcheck.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306 33060
CMD ["mysqld"]
HEALTHCHECK --interval=5s --retries=5 CMD ["/healthcheck.sh"]
