FROM UPSTREAM_REPO

ARG MYSQL_PACKAGE_VERSION=5.6.31-2
ENV MYSQL_PACKAGE_VERSION=$MYSQL_PACKAGE_VERSION
ENV PACKAGE_URL https://repo.mysql.com/yum/mysql-5.6-community/docker/x86_64/mysql-community-server-minimal-$MYSQL_PACKAGE_VERSION.el7.x86_64.rpm
ENV MYSQL_DATABASE data
ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_MAX_ALLOWED_PACKET 16m

# Install server
RUN rpmkeys --import http://repo.mysql.com/RPM-GPG-KEY-mysql \
  && yum install -y $PACKAGE_URL \
  && yum install -y libpwquality \
  && rm -rf /var/cache/yum/*

RUN mkdir /docker-entrypoint-initdb.d

VOLUME /var/lib/mysql

ADD files /
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306
CMD ["mysqld"]

